CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_me VARCHAR(255),
    anything_else VARCHAR(255),
    custom_prompt VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    what_do_you_do VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS public.threads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_threads_user FOREIGN KEY (user_id)
      REFERENCES public.users (id)
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_llm_generated BOOLEAN NOT NULL,
    completion_model VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    file_url VARCHAR(255),
    thread_id BIGINT NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_messages_thread FOREIGN KEY (thread_id)
       REFERENCES public.threads (id)
       ON UPDATE NO ACTION
       ON DELETE NO ACTION,
    CONSTRAINT fk_messages_user FOREIGN KEY (user_id)
       REFERENCES public.users (id)
       ON UPDATE NO ACTION
       ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.user_traits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trait VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_user_traits_user FOREIGN KEY (user_id)
      REFERENCES public.users (id)
      ON UPDATE NO ACTION
      ON DELETE CASCADE
);


